### ISSUE TITLE
Compilation error with GCC

### ISSUE THREAD

**Issue by keipertk** [jkwack/GAMESS_RI-MP2_MiniApp#1]
Hello,
 I'm attempting to compile with GCC v8.3.0. I get the following error:

```
~/GAMESS_RI-MP2_MiniApp$ mpifort -fopenmp -foffload="-lm" -DNVBLAS -g -cpp source//rimp2_energy_whole_KERN.f90 -o rimp2-nvblas -lnvblas 
source//rimp2_energy_whole_KERN.f90:300:51:

         !$omp target data use_device_ptr(BI,BJ,QVV)

Error: TARGET DATA must contain at least one MAP clause at (1)
```

Any advice? Or is GCC unsupported for now?

Thanks,
  Kris

**Comment by jkwack** [comment]
Hi, Kris.

This is a bug of GCC. It was reported by Nick Romero. I hope the next version will resolve the issue.

Best,
JaeHyuk


On Feb 25, 2020, at 1:29 PM, Kristopher Keipert <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,
I'm attempting to compile with GCC v8.3.0. I get the following error:

~/GAMESS_RI-MP2_MiniApp$ mpifort -fopenmp -foffload="-lm" -DNVBLAS -g -cpp source//rimp2_energy_whole_KERN.f90 -o rimp2-nvblas -lnvblas
source//rimp2_energy_whole_KERN.f90:300:51:

         !$omp target data use_device_ptr(BI,BJ,QVV)

Error: TARGET DATA must contain at least one MAP clause at (1)


Any advice? Or is GCC unsupported for now?

Thanks,
Kris

**Comment by keipertk** [comment]
Thanks. Issue persists with GCC 9.2.0. Fingers crossed for GCC 10.

**Comment by jkwack** [comment]
You are right. The feature is not supported by up to GCC 9.2.0.  See the GCC bug 92311 at the following link:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92311
Hopefully, GCC 10 will support this feature.

**Comment by keipertk** [comment]
Thanks for the link. It looks like it is very unlikely to appear in GCC 10.  Is there any way to mitigate this error for now by providing a map clause that will give the same program behavior? If not, I'll use a different compiler for now.

**Comment by jkwack** [comment]
We may add a dummy map clause for GCC. I will try it and keep you updated.

**Comment by jkwack** [comment]
I just added map(to:E2) on the line and gfortran doesn't complain it any more. See the following:
[Before]

> bash-4.2$ head -n 299 source/rimp2_energy_whole_KERN.f90 | tail -n 1
>         !$omp target data use_device_ptr(BI,BJ,QVV)
> bash-4.2$ mpifort -fopenmp -foffload="-lm" -DNVBLAS -g -cpp source/rimp2_energy_whole_KERN.f90 -o rimp2-nvblas -L/sw/summit/cuda/10.1.168/lib64 -lnvblas -L${OLCF_ESSL_ROOT}/lib64 -lessl
> source/rimp2_energy_whole_KERN.f90:299:51:
> 
>   299 |         !$omp target data use_device_ptr(BI,BJ,QVV)
>       |                                                   1
> Error: TARGET DATA must contain at least one MAP clause at (1)

[after]

> bash-4.2$ head -n 299 source/rimp2_energy_whole_KERN.f90 | tail -n 1
>         !$omp target data map(to:E2) use_device_ptr(BI,BJ,QVV)
> bash-4.2$ mpifort -fopenmp -foffload="-lm" -DNVBLAS -g -cpp source/rimp2_energy_whole_KERN.f90 -o rimp2-nvblas -L/sw/summit/cuda/10.1.168/lib64 -lnvblas -L${OLCF_ESSL_ROOT}/lib64 -lessl


I will update the GitHub repository soon.

**Comment by jkwack** [comment]
Hmm, it seems GNU has another problem:

> bash-4.2$ EXEC=rimp2-nvblas INPUT=20 ./run_gpu.sh 
> Running this script with 1 node(s) with up to 6 GPUs:
>    NMPI is set to 1. For another NMPI, use NMPI=x before this job script.
>    INPUT is set to 20.
>    EXEC is set to rimp2-nvblas.
> 
> 
> [[[Running rimp2-nvblas with 1 MPI rank(s)...]]]
> [NVBLAS] NVBLAS_CONFIG_FILE environment variable is NOT set : relying on default config filename 'nvblas.conf'
> [NVBLAS] Cannot Log File 'nvblas.log'
> [NVBLAS] Using devices :0 
> [NVBLAS] Config parsed
>  You are running the code with nvblas on GPU
>      Generating arbitrary input data with the structure of 20 water clusters
>      NAUXBASD,NCOR,NACT,NVIR,NBF =   1680    20    80   380   500
>      NQVV =        80
>      Memory Footprint:
>           B32(  638400,     80) =    408.5760 MB
>           eij(      80,     80) =      0.0512 MB
>           eab(     380,    380) =      1.1552 MB
>           QVV(  380,  80,  380) =     92.4160 MB
> 
> libgomp: GOMP_target_enter_exit_data unhandled kind 0x05
> 
> 
> 

I recommend you to use a different compiler. Sorry. 
I won't push the updated file with the dummy map clause, since it doesn't resolve the issue.

**Comment by jkwack** [comment]
Another GNU bug (92311):
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91762

It won't be fixed until GCC11. Please use a different compiler.

**Comment by jkwack** [comment]
I am closing this issue, since it comes from limited OpenMP offloading supports of gfortran compiler.

**Comment by keipertk** [comment]
Thanks, I'll use a different compiler. BTW the second bug is reported by a core developer of NWChem - it seems GCC is unkind to quantum chemists these days =D
